#!/usr/bin/node --harmony_rest_parameters
'use strict';

let net = require('net'),
    serverFunc = require('./module/server'),
    args = require('./module/arguments')(),
    config = require('./assets/config/server.json'),

    port = args.port || config.port || 1100,

    server = net.createServer(serverFunc);

server.listen(port, () => {
    console.log('Server started at port:', port);
});
